GRANT ALL ON PUB."Benefits" TO PUBLIC
GO
GRANT ALL ON PUB."BillTo" TO PUBLIC
GO
GRANT ALL ON PUB."Bin" TO PUBLIC
GO
GRANT ALL ON PUB."Customer" TO PUBLIC
GO
GRANT ALL ON PUB."Department" TO PUBLIC
GO
GRANT ALL ON PUB."Employee" TO PUBLIC
GO
GRANT ALL ON PUB."Family" TO PUBLIC
GO
GRANT ALL ON PUB."Feedback" TO PUBLIC
GO
GRANT ALL ON PUB."InventoryTrans" TO PUBLIC
GO
GRANT ALL ON PUB."Invoice" TO PUBLIC
GO
GRANT ALL ON PUB."Item" TO PUBLIC
GO
GRANT ALL ON PUB."LocalDefault" TO PUBLIC
GO
GRANT ALL ON PUB."Order" TO PUBLIC
GO
GRANT ALL ON PUB."OrderLine" TO PUBLIC
GO
GRANT ALL ON PUB."POLine" TO PUBLIC
GO
GRANT ALL ON PUB."PurchaseOrder" TO PUBLIC
GO
GRANT ALL ON PUB."RefCall" TO PUBLIC
GO
GRANT ALL ON PUB."SalesRep" TO PUBLIC
GO
GRANT ALL ON PUB."ShipTo" TO PUBLIC
GO
GRANT ALL ON PUB."State" TO PUBLIC
GO
GRANT ALL ON PUB."Supplier" TO PUBLIC
GO
GRANT ALL ON PUB."SupplierItemXref" TO PUBLIC
GO
GRANT ALL ON PUB."TimeSheet" TO PUBLIC
GO
GRANT ALL ON PUB."Vacation" TO PUBLIC
GO
GRANT ALL ON PUB."Warehouse" TO PUBLIC
GO
