#C:\projects\pasoem8m\m8m\SQLExplorer.properties
#16 Mar 2025, 12:00:40
EchoSql=false
Connect=jdbc:datadirect:openedge://localhost:5151;databaseName=sports2000
AutoCommit=false
HasFetchLimit=true
ColumnWidthLimit=25
ColumnWidthMinimum=1
HasColumnLimit=false
Logging=false
EchoAll=false
SqlVerbose=false
FetchLimit=101
ReportFormat=Standard
DisableWarnings=true
Pager=false
Run=
Logfile=C:\projects\pasoem8m\m8m\SQLExplorerSession.log
ConnectTimeout=180
EchoComments=false
ResultSetLimit=24
TableFormat=true
Help=
TransactionIsolation=Read Committed
PageLimit=22
Echo=true
Show=
Reset=
Disconnect=true
UseUrlFormat=false
EchoCmd=false
