
/*------------------------------------------------------------------------
    File        : web.api.mcp.methodenum
    Author(s)   : colde
  ----------------------------------------------------------------------*/

ENUM web.api.mcp.methodenum :  
 
 DEFINE ENUM    Initialize
                Notifications_Initialized
                Notifications_Cancelled
                Resources_List
                Tools_List
                Tools_Call.

END ENUM.